### ISSUE TITLE
Fix Bug in Reservation Service 

### ISSUE THREAD

**Issue by bheesham08** [faiz2497/OpenSourceAssg4#25]
Unable to get reservations for date

**Comment by bheesham08** [comment]
https://github.com/faiz2497/OpenSourceAssg4/pull/29

**Comment by bheesham08** [comment]
https://github.com/faiz2497/OpenSourceAssg4/pull/31

**Comment by bheesham08** [comment]
Added implementation
please Review @Vishali2499 @faiz2497 @richa12gmail

**Comment by Vishali2499** [comment]
@bheesham08  Looks good.
